export const constances = {
    FETCH_ALBUMS_PENDING: 'FETCH_ALBUMS_PENDING',
    FETCH_ALBUMS_SUCCESS: 'FETCH_ALBUMS_SUCCESS',
    FETCH_ALBUMS_ERROR: 'FETCH_ALBUMS_ERROR',

    SET_ARTIST_IDS: 'SET_ARTIST_IDS',
    FETCH_ARTISTS_PENDING: 'FETCH_ARTISTS_PENDING',
    FETCH_ARTISTS_SUCCESS: 'FETCH_ARTISTS_SUCCESS',
    FETCH_ARTISTS_ERROR: 'FETCH_ARTISTS_ERROR',

    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_ERROR: 'FETCH_CATEGORIES_ERROR',
    FETCH_NEW_RELEASES_SUCCESS: 'FETCH_NEW_RELEASES_SUCCESS',
    FETCH_NEW_RELEASES_ERROR: 'FETCH_NEW_RELEASES_ERROR',
    FETCH_FEATURED_SUCCESS: 'FETCH_FEATURED_SUCCESS',
    FETCH_FEATURED_ERROR: 'FETCH_FEATURED_ERROR',
    FETCH_GENRE_SUCCESS: 'FETCH_GENRE_SUCCESS',
    FETCH_GENRE_ERROR: 'FETCH_GENRE_ERROR',

    FETCH_FRIENDSLIST_SUCCESS: 'FETCH_FRIENDSLIST_SUCCESS',
    UPDATE_CURRENT_CONNECTING: 'UPDATE_CURRENT_CONNECTING',
    FETCH_USER_INFO: 'FETCH_USER_INFO',

    FETCH_MESSAGES: 'FETCH_MESSAGES',

    FETCH_PLAYLIST_MENU_PENDING: 'FETCH_PLAYLIST_MENU_PENDING',
    FETCH_PLAYLIST_MENU_SUCCESS: 'FETCH_PLAYLIST_MENU_SUCCESS',
    ADD_PLAYLIST_ITEM: 'ADD_PLAYLIST_ITEM',
    FETCH_PLAYLIST_MENU_ERROR: 'FETCH_PLAYLIST_MENU_ERROR',
    FETCH_USER_PLAYLIST: 'FETCH_USER_PLAYLIST',
    CREATE_PLAYLIST: 'CREATE_PLAYLIST',
    REMOVE_PLAYLIST: 'REMOVE_PLAYLIST',
    UPDATE_USER_PLAYLIST: 'UPDATE_USER_PLAYLIST',
    ADD_INTO_PLAYLIST: 'ADD_INTO_PLAYLIST',

    UPDATE_VIEW_TYPE: 'UPDATE_VIEW_TYPE',
    FETCH_SONGS_PENDING: 'FETCH_SONGS_PENDING',
    FETCH_SONGS_SUCCESS: 'FETCH_SONGS_SUCCESS',
    FETCH_SONGS_ERROR: 'FETCH_SONGS_ERROR',
    SEARCH_SONGS_PENDING: 'SEARCH_SONGS_PENDING',
    SEARCH_SONGS_SUCCESS: 'SEARCH_SONGS_SUCCESS',
    SEARCH_SONGS_ERROR: 'SEARCH_SONGS_ERROR',
    FETCH_RECENTLY_PLAYED_PENDING: 'FETCH_RECENTLY_PLAYED_PENDING',
    FETCH_RECENTLY_PLAYED_SUCCESS: 'FETCH_RECENTLY_PLAYED_SUCCESS',
    FETCH_RECENTLY_PLAYED_ERROR: 'FETCH_RECENTLY_PLAYED_ERROR',
    FETCH_PLAYLIST_SONGS_PENDING: 'FETCH_PLAYLIST_SONGS_PENDING',
    FETCH_PLAYLIST_SONGS_SUCCESS: 'FETCH_PLAYLIST_SONGS_SUCCESS',
    FETCH_PLAYLIST_SONGS_ERROR: 'FETCH_PLAYLIST_SONGS_ERROR',
    FETCH_ARTIST_SONGS_PENDING: 'FETCH_ARTIST_SONGS_PENDING',
    FETCH_ARTIST_SONGS_SUCCESS: 'FETCH_ARTIST_SONGS_SUCCESS',
    FETCH_ARTIST_SONGS_ERROR: 'FETCH_ARTIST_SONGS_ERROR',
    PLAY_SONG: 'PLAY_SONG',
    STOP_SONG: 'STOP_SONG',
    PAUSE_SONG: 'PAUSE_SONG',
    RESUME_SONG: 'RESUME_SONG',
    INCREASE_SONG_TIME: 'INCREASE_SONG_TIME',

    UPDATE_VOLUME: 'UPDATE_VOLUME',

    SET_TOKEN: 'SET_TOKEN',

    UPDATE_HEADER_TITLE: 'UPDATE_HEADER_TITLE',

    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_ERROR: 'FETCH_USER_ERROR',
    ADD_SONG_TO_LIBRARY_SUCCESS: 'ADD_SONG_TO_LIBRARY_SUCCESS',
    ADD_SONG_TO_LIBRARY_ERROR: 'ADD_SONG_TO_LIBRARY_ERROR',
    REMOVE_SONG_FROM_LIBRARY: 'REMOVE_SONG_FROM_LIBRARY',

    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    SENT_MESSAGE: 'SENT_MESSAGE',
    READ_NEW_MESSAGE: 'READ_NEW_MESSAGE'
}